<?php

use Illuminate\Database\Seeder;
use App\Models\Admin\Menu;
class MenuTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $menu = [
            [
                'name'=>'权限管理',
                'icon'=>'el-icon-cpu',
                'path'=>'/auth',
                'component'=>'#',
                'redirect'=>'/auth/menu',
                'type'=>1,
                'status'=>1,
                'permission'=>'permission',
                "children"=>[
                    [
                        'name'=>'管理员管理',
                        'icon'=>'',
                        'path'=>'user',
                        'permission'=>'user',
                        'component'=>'user/index',
                        'type'=>2,
                        'status'=>1,
                        "children"=>[
                            [
                                'name'=>'列表',
                                'icon'=>'',
                                'permission'=>'user:index',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'添加',
                                'icon'=>'',
                                'permission'=>'user:create',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'查看',
                                'icon'=>'',
                                'permission'=>'user:edit',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'保存',
                                'icon'=>'',
                                'permission'=>'user:update',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'删除',
                                'icon'=>'',
                                'permission'=>'user:delete',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'批量删除',
                                'icon'=>'',
                                'permission'=>'user:delAll',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'状态',
                                'icon'=>'',
                                'permission'=>'user:status',
                                'type'=>3,
                                'status'=>1,
                            ],
                        ]
                    ],
                    [
                        'name'=>'角色管理',
                        'icon'=>'',
                        'path'=>'role',
                        'permission'=>'role',
                        'component'=>'role/index',
                        'type'=>2,
                        'status'=>1,
                        "children"=>[
                            [
                                'name'=>'列表',
                                'icon'=>'',
                                'permission'=>'role:index',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'添加',
                                'icon'=>'',
                                'permission'=>'role:create',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'查看',
                                'icon'=>'',
                                'permission'=>'role:edit',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'保存',
                                'icon'=>'',
                                'permission'=>'role:update',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'删除',
                                'icon'=>'',
                                'permission'=>'role:delete',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'批量删除',
                                'icon'=>'',
                                'permission'=>'role:delAll',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'状态',
                                'icon'=>'',
                                'permission'=>'role:status',
                                'type'=>3,
                                'status'=>1,
                            ],
                        ]
                    ],
                    [
                        'name'=>'菜单管理',
                        'icon'=>'',
                        'path'=>'menu',
                        'permission'=>'menu',
                        'component'=>'menu/index',
                        'type'=>2,
                        'status'=>1,
                        "children"=>[
                            [
                                'name'=>'列表',
                                'icon'=>'',
                                'permission'=>'menu:index',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'添加',
                                'icon'=>'',
                                'permission'=>'menu:create',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'查看',
                                'icon'=>'',
                                'permission'=>'menu:edit',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'保存',
                                'icon'=>'',
                                'permission'=>'menu:update',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'删除',
                                'icon'=>'',
                                'permission'=>'menu:delete',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'批量删除',
                                'icon'=>'',
                                'permission'=>'menu:delAll',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'状态',
                                'icon'=>'',
                                'permission'=>'menu:status',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'全部展开',
                                'icon'=>'',
                                'permission'=>'menu:expandAll',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'全部折叠',
                                'icon'=>'',
                                'permission'=>'menu:foldAll',
                                'type'=>3,
                                'status'=>1,
                            ],
                        ]
                    ],
                    [
                        'name'=>'日志管理',
                        'icon'=>'',
                        'path'=>'actionlog',
                        'permission'=>'actionlog',
                        'component'=>'actionlog/index',
                        'type'=>2,
                        'status'=>1,
                        "children"=>[
                            [
                                'name'=>'列表',
                                'icon'=>'',
                                'permission'=>'actionlog:index',
                                'type'=>3,
                                'status'=>1,
                            ],
                        ]
                    ],
                ],
            ],
            [
                'name'=>'常规管理',
                'icon'=>'el-icon-s-tools',
                'path'=>'/system',
                'component'=>'#',
                'redirect'=>'/config/menu',
                'permission'=>'config',
                'type'=>1,
                'status'=>1,
                "children"=>[
                    [
                        'name'=>'区域',
                        'icon'=>'',
                        'path'=>'city',
                        'permission'=>'city',
                        'component'=>'system/city/index',
                        'type'=>2,
                        'status'=>1,
                        "children"=>[
                            [
                                'name'=>'列表',
                                'icon'=>'',
                                'permission'=>'city:index',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'添加',
                                'icon'=>'',
                                'permission'=>'city:create',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'查看',
                                'icon'=>'',
                                'permission'=>'city:edit',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'保存',
                                'icon'=>'',
                                'permission'=>'city:update',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'删除',
                                'icon'=>'',
                                'permission'=>'city:delete',
                                'type'=>3,
                                'status'=>1,
                            ],
                        ],
                    ],
                    [
                        'name'=>'系统设置',
                        'icon'=>'',
                        'path'=>'settings',
                        'permission'=>'settings',
                        'component'=>'system/settings',
                        'type'=>2,
                        'status'=>1,
                        "children"=>[
                            [
                                'name'=>'列表',
                                'icon'=>'',
                                'permission'=>'settings:index',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'添加',
                                'icon'=>'',
                                'permission'=>'settings:create',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'查看',
                                'icon'=>'',
                                'permission'=>'settings:edit',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'保存',
                                'icon'=>'',
                                'permission'=>'settings:update',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'删除',
                                'icon'=>'',
                                'permission'=>'settings:delete',
                                'type'=>3,
                                'status'=>1,
                            ],
                        ]
                    ],
                    [
                        'name'=>'代码生成',
                        'icon'=>'',
                        'path'=>'code',
                        'permission'=>'code',
                        'component'=>'system/code',
                        'type'=>2,
                        'status'=>1,
                        "children"=>[
                            [
                                'name'=>'保存',
                                'icon'=>'',
                                'permission'=>'code:update',
                                'type'=>3,
                                'status'=>1,
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name'=>'运维管理',
                'icon'=>'',
                'path'=>'/operation',
                'permission'=>'operation',
                'redirect'=>'/operation/crontab',
                'component'=>'#',
                'type'=>1,
                'status'=>1,
                "children"=>[
                    [
                        'name'=>'定时任务',
                        'icon'=>'',
                        'path'=>'crontab',
                        'permission'=>'crontab',
                        'component'=>'crontab/index',
                        'type'=>2,
                        'status'=>1,
                        "children"=>[
                            [
                                'name'=>'列表',
                                'icon'=>'',
                                'permission'=>'crontab:index',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'添加',
                                'icon'=>'',
                                'permission'=>'crontab:create',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'查看',
                                'icon'=>'',
                                'permission'=>'crontab:edit',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'保存',
                                'icon'=>'',
                                'permission'=>'crontab:update',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'删除',
                                'icon'=>'',
                                'permission'=>'crontab:delete',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'状态',
                                'icon'=>'',
                                'permission'=>'crontab:status',
                                'type'=>3,
                                'status'=>1,
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name'=>'用户管理',
                'icon'=>'',
                'path'=>'/member',
                'permission'=>'member',
                'redirect'=>'/member/index',
                'component'=>'#',
                'type'=>1,
                'status'=>1,
                "children"=>[
                    [
                        'name'=>'用户列表',
                        'icon'=>'',
                        'path'=>'index',
                        'permission'=>'member',
                        'component'=>'member/index',
                        'type'=>2,
                        'status'=>1,
                        "children"=>[
                            [
                                'name'=>'列表',
                                'icon'=>'',
                                'permission'=>'member:index',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'添加',
                                'icon'=>'',
                                'permission'=>'member:create',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'查看',
                                'icon'=>'',
                                'permission'=>'member:edit',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'保存',
                                'icon'=>'',
                                'permission'=>'member:update',
                                'type'=>3,
                                'status'=>1,
                            ],
                            [
                                'name'=>'状态',
                                'icon'=>'',
                                'permission'=>'member:status',
                                'type'=>3,
                                'status'=>1,
                            ],
                        ]
                    ]
                ]
            ]
        ];
        $menu = $this->recursion($menu);
        foreach ($menu as $m){
            Menu::create($m);
        }
        dump('菜单添加 success');
        // 角色权限
        for ($i = 0; $i < count($menu); $i++) {
            $role_menu[]=['menu_id' => $menu[$i]['id'],'role_id' => 1];
        }
        \DB::table('role_menu')->insert($role_menu);

        dump('角色权限添加 success');
    }
    protected function recursion($menu, $pid = 0){
        global $res;
        foreach ($menu as &$m){
            global $id;
            if (!$m['id']){
                $m['id'] = ++$id;
            }
            if ($pid){
                $m['pid'] = $pid;
            }
            if (is_array ($m['children']))
            {
                $m['children'] = $this->recursion ($m['children'],$id);
                unset($m['children']);
            }
            $res[] = $m;
        }
        return $res;
    }
}
