<?php
$arr = [
    [
        'name'=>'权限管理',
        'icon'=>'',
        'path'=>'/auth',
        'component'=>'#',
        'redirect'=>'/auth/menu',
        'type'=>1,
        'status'=>1,
        'permission'=>'permission',
        "children"=>[
            [
                'name'=>'管理员管理',
                'icon'=>'',
                'path'=>'user',
                'permission'=>'user',
                'component'=>'user/index',
                'type'=>2,
                'status'=>1,
                "children"=>[
                    [
                        'name'=>'列表',
                        'icon'=>'',
                        'permission'=>'user:index',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'添加',
                        'icon'=>'',
                        'permission'=>'user:create',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'查看',
                        'icon'=>'',
                        'permission'=>'user:edit',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'保存',
                        'icon'=>'',
                        'permission'=>'user:update',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'删除',
                        'icon'=>'',
                        'permission'=>'user:del',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'批量删除',
                        'icon'=>'',
                        'permission'=>'user:delAll',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'状态',
                        'icon'=>'',
                        'permission'=>'user:status',
                        'type'=>3,
                        'status'=>1,
                    ],
                ]
            ],
            [
                'name'=>'角色管理',
                'icon'=>'',
                'path'=>'role',
                'permission'=>'role',
                'component'=>'role/index',
                'type'=>2,
                'status'=>1,
                "children"=>[
                    [
                        'name'=>'列表',
                        'icon'=>'',
                        'permission'=>'role:index',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'添加',
                        'icon'=>'',
                        'permission'=>'role:create',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'查看',
                        'icon'=>'',
                        'permission'=>'role:edit',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'保存',
                        'icon'=>'',
                        'permission'=>'role:update',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'删除',
                        'icon'=>'',
                        'permission'=>'role:del',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'批量删除',
                        'icon'=>'',
                        'permission'=>'role:delAll',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'状态',
                        'icon'=>'',
                        'permission'=>'role:status',
                        'type'=>3,
                        'status'=>1,
                    ],
                ]
            ],
            [
                'name'=>'菜单管理',
                'icon'=>'',
                'path'=>'menu',
                'permission'=>'menu',
                'component'=>'menu/index',
                'type'=>2,
                'status'=>1,
                "children"=>[
                    [
                        'name'=>'列表',
                        'icon'=>'',
                        'permission'=>'menu:index',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'添加',
                        'icon'=>'',
                        'permission'=>'menu:create',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'查看',
                        'icon'=>'',
                        'permission'=>'menu:edit',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'保存',
                        'icon'=>'',
                        'permission'=>'menu:update',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'删除',
                        'icon'=>'',
                        'permission'=>'menu:del',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'批量删除',
                        'icon'=>'',
                        'permission'=>'menu:delAll',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'状态',
                        'icon'=>'',
                        'permission'=>'menu:status',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'全部展开',
                        'icon'=>'',
                        'permission'=>'menu:expandAll',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'全部折叠',
                        'icon'=>'',
                        'permission'=>'menu:foldAll',
                        'type'=>3,
                        'status'=>1,
                    ],
                ]
            ],
            [
                'name'=>'日志管理',
                'icon'=>'',
                'path'=>'actionlog',
                'permission'=>'actionlog',
                'component'=>'actionlog/index',
                'type'=>2,
                'status'=>1,
                "children"=>[
                    [
                        'name'=>'列表',
                        'icon'=>'',
                        'permission'=>'actionlog:index',
                        'type'=>3,
                        'status'=>1,
                    ],
                ]
            ],
        ],
    ],
    [
        'name'=>'常规管理',
        'icon'=>'',
        'path'=>'/general',
        'component'=>'#',
        'redirect'=>'/config/menu',
        'permission'=>'config',
        'type'=>1,
        'status'=>1,
        "children"=>[
            [
                'name'=>'区域',
                'icon'=>'',
                'path'=>'city',
                'permission'=>'city',
                'component'=>'general/city/index',
                'type'=>2,
                'status'=>1,
                "children"=>[
                    [
                        'name'=>'列表',
                        'icon'=>'',
                        'permission'=>'city:index',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'添加',
                        'icon'=>'',
                        'permission'=>'city:create',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'查看',
                        'icon'=>'',
                        'permission'=>'city:edit',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'保存',
                        'icon'=>'',
                        'permission'=>'city:update',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'删除',
                        'icon'=>'',
                        'permission'=>'city:del',
                        'type'=>3,
                        'status'=>1,
                    ],
                ],
            ],
            [
                'name'=>'系统设置',
                'icon'=>'',
                'path'=>'config',
                'permission'=>'config',
                'component'=>'general/config',
                'type'=>2,
                'status'=>1,
                "children"=>[
                    [
                        'name'=>'列表',
                        'icon'=>'',
                        'permission'=>'config:index',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'添加',
                        'icon'=>'',
                        'permission'=>'config:create',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'查看',
                        'icon'=>'',
                        'permission'=>'config:edit',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'保存',
                        'icon'=>'',
                        'permission'=>'config:update',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'删除',
                        'icon'=>'',
                        'permission'=>'config:del',
                        'type'=>3,
                        'status'=>1,
                    ],
                ]
            ],
            [
                'name'=>'代码生成',
                'icon'=>'',
                'path'=>'code',
                'permission'=>'code',
                'component'=>'general/code',
                'type'=>2,
                'status'=>1,
                "children"=>[
                    [
                        'name'=>'保存',
                        'icon'=>'',
                        'permission'=>'code:update',
                        'type'=>3,
                        'status'=>1,
                    ],
                ]
            ],
        ]
    ],
    [
        'name'=>'运维管理',
        'icon'=>'',
        'path'=>'operation',
        'permission'=>'operation',
        'component'=>'general/config',
        'type'=>2,
        'status'=>1,
        "children"=>[
            [
                'name'=>'定时任务',
                'icon'=>'',
                'path'=>'crontab',
                'permission'=>'crontab',
                'component'=>'general/crontab',
                'type'=>2,
                'status'=>1,
                "children"=>[
                    [
                        'name'=>'列表',
                        'icon'=>'',
                        'permission'=>'crontab:index',
                        'type'=>3,
                        'status'=>1,
                    ],
                    [
                        'name'=>'保存',
                        'icon'=>'',
                        'permission'=>'crontab:update',
                        'type'=>3,
                        'status'=>1,
                    ],
                ]
            ],
        ]
    ],
];

function recursion($menu,$pid = 0){
    global $res;
    foreach ($menu as &$m){
        global $id;
        if (!@$m['id']){
            $m['id'] = ++$id;
        }
        if ($pid){
            $m['pid'] = $pid;
        }
        if (is_array ($m['children']))
        {
            $m['children'] = recursion ($m['children'],$id);
            unset($m['children']);
        }
        $res[] = $m;
    }
    return $res;
}

$arr = recursion($arr);

var_dump($arr);